# backup-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo-backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backup-pvc
  namespace: edugo-auth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
