apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  namespace: edugo-auth
  labels:
    app: mongo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exporter
  template:
    metadata:
      labels:
        app: mongo-exporter
    spec:
      containers:
        - name: exporter
          image: bitnami/mongodb-exporter:latest
          args:
            # MongoDB connection
            - "--mongodb.uri=mongodb://authuser:authpass@mongo-standalone:27017/?authSource=admin"
            # Enable all core collectors
            - "--collect.general"
            - "--collect.database"
            - "--collect.indexstats"
            - "--collect.replset"
            - "--collect.topmetrics"
            - "--collect.connections"
            - "--collect.opcounters"
            - "--collect.opcountersrepl"
            - "--collect.serverStatus"
          ports:
            - name: metrics
              containerPort: 9216
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9216
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9216
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exporter
  namespace: edugo-auth
  labels:
    app: mongo-exporter
spec:
  selector:
    app: mongo-exporter
  ports:
    - name: metrics
      port: 9216
      targetPort: 9216
