#mongo-standalone.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-standalone
  namespace: edugo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-standalone
  template:
    metadata:
      labels:
        app: mongo-standalone
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          args:
            - mongod
            - "--bind_ip_all"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-standalone
  namespace: edugo-auth
spec:
  selector:
    app: mongo-standalone
  ports:
    - port: 27017
      targetPort: 27017
